flowchart LR
    subgraph docker_ai_tools
        docker__ai_tools__entrypoint__print["print"]
    end
    subgraph llx_analysis
        llx__analysis__collector___collect_filesystem_metrics["_collect_filesystem_metrics"]
        llx__analysis__collector___apply_analysis_yaml["_apply_analysis_yaml"]
        llx__analysis__collector___parse_map_hotspots_line["_parse_map_hotspots_line"]
        llx__analysis__collector___load_file["_load_file"]
        llx__analysis__collector___collect_redup_metrics["_collect_redup_metrics"]
        llx__analysis__collector___collect_vallm_metrics["_collect_vallm_metrics"]
        llx__analysis__runner__run_redup["run_redup"]
        llx__analysis__collector___parse_map_stats_line["_parse_map_stats_line"]
        llx__analysis__runner__run_code2llm["run_code2llm"]
        llx__analysis__collector___apply_map_yaml["_apply_map_yaml"]
        llx__analysis__collector___collect_code2llm_metrics["_collect_code2llm_metrics"]
        llx__analysis__collector__analyze_project["analyze_project"]
        llx__analysis__collector___count_map_modules["_count_map_modules"]
        llx__analysis__collector___extract_evolution_stats["_extract_evolution_stats"]
        llx__analysis__collector___parse_map_alerts_line["_parse_map_alerts_line"]
        llx__analysis__collector___extract_evolution_actions["_extract_evolution_actions"]
        llx__analysis__runner___run_tool["_run_tool"]
        llx__analysis__collector___classify_scope["_classify_scope"]
        llx__analysis__collector___apply_evolution_yaml["_apply_evolution_yaml"]
        llx__analysis__collector___estimate_context_tokens["_estimate_context_tokens"]
        llx__analysis__collector___apply_map_text["_apply_map_text"]
        llx__analysis__runner__run_all_tools["run_all_tools"]
        llx__analysis__runner__check_tool["check_tool"]
        llx__analysis__runner__run_vallm["run_vallm"]
        llx__analysis__collector___extract_metrics_target["_extract_metrics_target"]
    end
    subgraph llx_cli
        llx__cli__app___run_analysis_tools["_run_analysis_tools"]
        llx__cli__formatters___build_title["_build_title"]
        llx__cli__app__select["select"]
        llx__cli__formatters___render_tools_table["_render_tools_table"]
        llx__cli__formatters__print_models_table["print_models_table"]
        llx__cli__formatters___render_models_table["_render_models_table"]
        llx__cli__formatters___render_tags_legend["_render_tags_legend"]
        llx__cli__app__proxy_config["proxy_config"]
        llx__cli__formatters___filter_models["_filter_models"]
        llx__cli__formatters___build_model_row["_build_model_row"]
        llx__cli__app__proxy_start["proxy_start"]
        llx__cli__app__models["models"]
        llx__cli__formatters___render_agents_table["_render_agents_table"]
        llx__cli__app__info["info"]
        llx__cli__formatters___render_tiers_table["_render_tiers_table"]
        llx__cli__formatters__print_info_tables["print_info_tables"]
        llx__cli__app__proxy_status["proxy_status"]
        llx__cli__app__chat["chat"]
    end
    subgraph llx_config
        llx__config___apply_yaml_proxy["_apply_yaml_proxy"]
        llx__config___apply_env["_apply_env"]
        llx__config___apply_yaml["_apply_yaml"]
        llx__config__LlxConfig__load["load"]
        llx__config___apply_yaml_thresholds["_apply_yaml_thresholds"]
    end
    subgraph llx_integrations
        llx__integrations__proxy__start_proxy["start_proxy"]
        llx__integrations__proxy__check_proxy["check_proxy"]
        llx__integrations__proxy__generate_proxy_config["generate_proxy_config"]
    end
    subgraph llx_litellm_config
        llx__litellm_config__LiteLLMConfig__load["load"]
        llx__litellm_config__load_litellm_config["load_litellm_config"]
    end
    subgraph llx_mcp
        llx__mcp__server__main_sync["main_sync"]
        llx__mcp__server__main["main"]
        llx__mcp__tools___handle_llx_analyze["_handle_llx_analyze"]
    end
    subgraph llx_orchestration
        llx__VSCodeOrchestrator__start_instance["start_instance"]
        llx__LLMOrchestrator___health_check_worker["_health_check_worker"]
        llx__LLMOrchestrator___create_default_config["_create_default_config"]
        llx__OrchestratorCLI___handle_restart["_handle_restart"]
        llx__RoutingEngine___optimization_worker["_optimization_worker"]
        llx__orchestration__llm_orchestrator__LLMOrchestrator__start["start"]
        llx__OrchestratorCLI___benchmark_queue["_benchmark_queue"]
        llx__LLMOrchestrator__add_provider["add_provider"]
        llx__OrchestratorCLI__run_command["run_command"]
        llx__orchestration__rate_limiter__RateLimiter__load_limits["load_limits"]
        llx__OrchestratorCLI___handle_stop["_handle_stop"]
        llx__OrchestratorCLI___handle_utils["_handle_utils"]
        llx__OrchestratorCLI___handle_start["_handle_start"]
        llx__OrchestratorCLI___handle_instance["_handle_instance"]
        llx__RoutingEngine___optimize_routing["_optimize_routing"]
        llx__VSCodeOrchestrator__remove_instance["remove_instance"]
        llx__VSCodeOrchestrator__create_instance["create_instance"]
        llx__VSCodeOrchestrator__remove_account["remove_account"]
        llx__RateLimiter__print_status_summary["print_status_summary"]
        llx__OrchestratorCLI___handle_queue["_handle_queue"]
        llx__RateLimiter___apply_penalty["_apply_penalty"]
        llx__RateLimiter___cleanup_worker["_cleanup_worker"]
        llx__orchestration__rate_limiter__RateLimiter__save_limits["save_limits"]
        llx__RoutingEngine__print_status_summary["print_status_summary"]
        llx__OrchestratorCLI___handle_config["_handle_config"]
        llx__VSCodeOrchestrator__start["start"]
        llx__RoutingEngine__save_config["save_config"]
        llx__OrchestratorCLI___benchmark_routing["_benchmark_routing"]
        llx__VSCodeOrchestrator__print_status_summary["print_status_summary"]
        llx__OrchestratorCLI___handle_rate_limit["_handle_rate_limit"]
        llx__OrchestratorCLI___handle_route["_handle_route"]
        llx__LLMOrchestrator__add_model["add_model"]
        llx__LLMOrchestrator___perform_health_checks["_perform_health_checks"]
        llx__orchestration__llm_orchestrator__LLMOrchestrator__stop["stop"]
        llx__RoutingEngine__load_config["load_config"]
        llx__VSCodeOrchestrator__load_config["load_config"]
        llx__VSCodeOrchestrator___start_browser_for_instance["_start_browser_for_instance"]
        llx__VSCodeOrchestrator__add_account["add_account"]
        llx__VSCodeOrchestrator___create_default_config["_create_default_config"]
        llx__VSCodeOrchestrator___session_cleanup_worker["_session_cleanup_worker"]
        llx__VSCodeOrchestrator___config_save_worker["_config_save_worker"]
        llx__VSCodeOrchestrator__stop["stop"]
        llx__OrchestratorCLI___handle_vscode["_handle_vscode"]
        llx__VSCodeOrchestrator__end_session["end_session"]
        llx__LLMOrchestrator__complete_request["complete_request"]
        llx__LLMOrchestrator__print_status_summary["print_status_summary"]
        llx__RateLimiter___cleanup_expired_penalties["_cleanup_expired_penalties"]
        llx__OrchestratorCLI___handle_status["_handle_status"]
        llx__VSCodeOrchestrator__save_config["save_config"]
        llx__LLMOrchestrator__load_config["load_config"]
        llx__LLMOrchestrator__remove_provider["remove_provider"]
        llx__OrchestratorCLI___handle_health["_handle_health"]
        llx__OrchestratorCLI___benchmark_rate_limiting["_benchmark_rate_limiting"]
        llx__orchestration__rate_limiter__RateLimiter__add_limit["add_limit"]
        llx__RoutingEngine__route_request["route_request"]
        llx__RoutingEngine___metrics_worker["_metrics_worker"]
        llx__LLMOrchestrator__save_config["save_config"]
        llx__OrchestratorCLI___handle_llm["_handle_llm"]
        llx__LLMOrchestrator__cancel_request["cancel_request"]
        llx__orchestration__rate_limiter__RateLimiter__remove_limit["remove_limit"]
        llx__OrchestratorCLI___handle_monitor["_handle_monitor"]
        llx__LLMOrchestrator___config_save_worker["_config_save_worker"]
        llx__OrchestratorCLI___handle_session["_handle_session"]
    end
    subgraph llx_routing
        llx__routing__selector__select_model["select_model"]
    end
    subgraph llx_tools
        llx__tools__model_manager__ModelManager__pull_model["pull_model"]
        llx__tools__model_manager__ModelManager__benchmark_model["benchmark_model"]
        llx__tools__ai_tools_manager__AIToolsManager__stop_ai_tools["stop_ai_tools"]
        llx__tools__config_manager__ConfigManager__load_config["load_config"]
        llx__tools__cli__LLXToolsCLI___handle_restart["_handle_restart"]
        llx__HealthChecker__run_quick_health_check["run_quick_health_check"]
        llx__AIToolsManager__restart_ai_tools["restart_ai_tools"]
        llx__tools__vscode_manager__VSCodeManager__start_vscode["start_vscode"]
        llx__tools__config_manager__ConfigManager__create_profile["create_profile"]
        llx__tools__cli__LLXToolsCLI___handle_status["_handle_status"]
        llx__tools__vscode_manager__VSCodeManager__backup_settings["backup_settings"]
        llx__tools__model_manager__ModelManager__print_model_summary["print_model_summary"]
        llx__tools__vscode_manager__VSCodeManager__restart_vscode["restart_vscode"]
        llx__ConfigManager__generate_docker_env_file["generate_docker_env_file"]
        llx__AIToolsManager__print_status_summary["print_status_summary"]
        llx__tools__cli__LLXToolsCLI__run_command["run_command"]
        llx__tools__vscode_manager__VSCodeManager__stop_vscode["stop_vscode"]
        llx__tools__cli__LLXToolsCLI___handle_health["_handle_health"]
        llx__tools__ai_tools_manager__AIToolsManager__update_tools["update_tools"]
        llx__VSCodeManager__create_launch_config["create_launch_config"]
        llx__tools__model_manager__ModelManager__test_model["test_model"]
        llx__tools__config_manager__ConfigManager__restore_configs["restore_configs"]
        llx__tools__cli__LLXToolsCLI___handle_utils["_handle_utils"]
        llx__AIToolsManager__print_usage_examples["print_usage_examples"]
        llx__AIToolsManager__backup_configurations["backup_configurations"]
        llx__tools__config_manager__ConfigManager__save_config["save_config"]
        llx__tools__model_manager__ModelManager__test_llx_model["test_llx_model"]
        llx__tools__cli__LLXToolsCLI___handle_stop["_handle_stop"]
        llx__ConfigManager__print_config_summary["print_config_summary"]
        llx__tools__vscode_manager__VSCodeManager__print_quick_start["print_quick_start"]
        llx__tools__ai_tools_manager__AIToolsManager__run_chat_test["run_chat_test"]
        llx__tools__cli__LLXToolsCLI___handle_docker["_handle_docker"]
        llx__tools__model_manager__ModelManager__remove_model["remove_model"]
        llx__ModelManager__cleanup_unused_models["cleanup_unused_models"]
        llx__tools__cli__LLXToolsCLI___handle_ai_tools["_handle_ai_tools"]
        llx__tools__config_manager__ConfigManager__list_models["list_models"]
        llx__VSCodeManager__create_workspace_tasks["create_workspace_tasks"]
        llx__AIToolsManager__restore_configurations["restore_configurations"]
        llx__tools__cli__LLXToolsCLI___handle_models["_handle_models"]
        llx__AIToolsManager__create_workspace_example["create_workspace_example"]
        llx__tools__vscode_manager__VSCodeManager__configure_roocode["configure_roocode"]
        llx__ModelManager__get_system_resources["get_system_resources"]
        llx__tools__config_manager__ConfigManager__remove_model["remove_model"]
        llx__HealthChecker___print_health_summary["_print_health_summary"]
        llx__ConfigManager__create_default_env["create_default_env"]
        llx__VSCodeManager__print_status_summary["print_status_summary"]
        llx__tools__health_checker__HealthChecker__monitor_services["monitor_services"]
        llx__HealthChecker__run_comprehensive_health_check["run_comprehensive_health_check"]
        llx__tools__ai_tools_manager__AIToolsManager__install_tool["install_tool"]
        llx__tools__cli__LLXToolsCLI___handle_start["_handle_start"]
        llx__tools__ai_tools_manager__AIToolsManager__access_shell["access_shell"]
        llx__VSCodeManager__uninstall_extension["uninstall_extension"]
        llx__VSCodeManager__wait_for_vscode_ready["wait_for_vscode_ready"]
        llx__VSCodeManager__install_extensions["install_extensions"]
        llx__tools__cli__LLXToolsCLI___handle_vscode["_handle_vscode"]
        llx__tools__config_manager__ConfigManager__load_profile["load_profile"]
        llx__tools__vscode_manager__VSCodeManager__restore_settings["restore_settings"]
        llx__tools__config_manager__ConfigManager__backup_configs["backup_configs"]
        llx__tools__vscode_manager__VSCodeManager__update_extensions["update_extensions"]
        llx__tools__cli__LLXToolsCLI___handle_config["_handle_config"]
        llx__tools__ai_tools_manager__AIToolsManager__start_ai_tools["start_ai_tools"]
        llx__ModelManager__create_model_profile["create_model_profile"]
    end
    llx__config__LlxConfig__load --> llx__litellm_config__LiteLLMConfig__load
    llx__config__LlxConfig__load --> llx__config___apply_env
    llx__config___apply_yaml --> llx__config___apply_yaml_proxy
    llx__config___apply_yaml --> llx__config___apply_yaml_thresholds
    llx__analysis__collector__analyze_project --> llx__analysis__collector___collect_filesystem_metrics
    llx__analysis__collector__analyze_project --> llx__analysis__collector___estimate_context_tokens
    llx__analysis__collector__analyze_project --> llx__analysis__collector___classify_scope
    llx__analysis__collector__analyze_project --> llx__analysis__collector___collect_code2llm_metrics
    llx__analysis__collector__analyze_project --> llx__analysis__collector___collect_redup_metrics
    llx__analysis__collector__analyze_project --> llx__analysis__collector___collect_vallm_metrics
    llx__analysis__collector___collect_code2llm_metrics --> llx__analysis__collector___load_file
    llx__analysis__collector___collect_code2llm_metrics --> llx__analysis__collector___apply_analysis_yaml
    llx__analysis__collector___collect_code2llm_metrics --> llx__analysis__collector___apply_evolution_yaml
    llx__analysis__collector___collect_code2llm_metrics --> llx__analysis__collector___apply_map_yaml
    llx__analysis__collector___apply_evolution_yaml --> llx__analysis__collector___extract_evolution_actions
    llx__analysis__collector___apply_evolution_yaml --> llx__analysis__collector___extract_metrics_target
    llx__analysis__collector___apply_evolution_yaml --> llx__analysis__collector___extract_evolution_stats
    llx__analysis__collector___apply_map_text --> llx__analysis__collector___count_map_modules
    llx__analysis__collector___apply_map_text --> llx__analysis__collector___parse_map_stats_line
    llx__analysis__collector___apply_map_text --> llx__analysis__collector___parse_map_alerts_line
    llx__analysis__collector___apply_map_text --> llx__analysis__collector___parse_map_hotspots_line
    llx__analysis__collector___collect_redup_metrics --> llx__analysis__collector___load_file
    llx__analysis__collector___collect_vallm_metrics --> llx__analysis__collector___load_file
    llx__tools__ai_tools_manager__AIToolsManager__start_ai_tools --> docker__ai_tools__entrypoint__print
    llx__tools__ai_tools_manager__AIToolsManager__stop_ai_tools --> docker__ai_tools__entrypoint__print
    llx__AIToolsManager__restart_ai_tools --> docker__ai_tools__entrypoint__print
    llx__tools__ai_tools_manager__AIToolsManager__access_shell --> docker__ai_tools__entrypoint__print
    llx__tools__ai_tools_manager__AIToolsManager__run_chat_test --> docker__ai_tools__entrypoint__print
    llx__tools__ai_tools_manager__AIToolsManager__install_tool --> docker__ai_tools__entrypoint__print
    llx__tools__ai_tools_manager__AIToolsManager__update_tools --> docker__ai_tools__entrypoint__print
    llx__AIToolsManager__create_workspace_example --> docker__ai_tools__entrypoint__print
    llx__AIToolsManager__backup_configurations --> docker__ai_tools__entrypoint__print
    llx__AIToolsManager__restore_configurations --> docker__ai_tools__entrypoint__print
    llx__AIToolsManager__print_status_summary --> docker__ai_tools__entrypoint__print
    llx__AIToolsManager__print_usage_examples --> docker__ai_tools__entrypoint__print
    llx__analysis__runner___run_tool --> llx__analysis__runner__check_tool
    llx__analysis__runner__run_code2llm --> llx__analysis__runner___run_tool
    llx__analysis__runner__run_redup --> llx__analysis__runner___run_tool
    llx__analysis__runner__run_vallm --> llx__analysis__runner___run_tool
    llx__tools__cli__LLXToolsCLI__run_command --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_start --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_stop --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_restart --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_status --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_health --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_docker --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_ai_tools --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_vscode --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_models --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_config --> docker__ai_tools__entrypoint__print
    llx__tools__cli__LLXToolsCLI___handle_utils --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__start_vscode --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__stop_vscode --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__restart_vscode --> docker__ai_tools__entrypoint__print
    llx__VSCodeManager__wait_for_vscode_ready --> docker__ai_tools__entrypoint__print
    llx__VSCodeManager__install_extensions --> docker__ai_tools__entrypoint__print
    llx__VSCodeManager__uninstall_extension --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__update_extensions --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__configure_roocode --> docker__ai_tools__entrypoint__print
    llx__VSCodeManager__create_workspace_tasks --> docker__ai_tools__entrypoint__print
    llx__VSCodeManager__create_launch_config --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__backup_settings --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__restore_settings --> docker__ai_tools__entrypoint__print
    llx__VSCodeManager__print_status_summary --> docker__ai_tools__entrypoint__print
    llx__tools__vscode_manager__VSCodeManager__print_quick_start --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__load_config --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__save_config --> docker__ai_tools__entrypoint__print
    llx__ConfigManager__create_default_env --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__remove_model --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__list_models --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__backup_configs --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__restore_configs --> docker__ai_tools__entrypoint__print
    llx__ConfigManager__generate_docker_env_file --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__create_profile --> docker__ai_tools__entrypoint__print
    llx__tools__config_manager__ConfigManager__load_profile --> docker__ai_tools__entrypoint__print
    llx__ConfigManager__print_config_summary --> docker__ai_tools__entrypoint__print
    llx__tools__model_manager__ModelManager__pull_model --> docker__ai_tools__entrypoint__print
    llx__tools__model_manager__ModelManager__remove_model --> docker__ai_tools__entrypoint__print
    llx__tools__model_manager__ModelManager__test_model --> docker__ai_tools__entrypoint__print
    llx__tools__model_manager__ModelManager__test_llx_model --> docker__ai_tools__entrypoint__print
    llx__ModelManager__get_system_resources --> docker__ai_tools__entrypoint__print
    llx__ModelManager__create_model_profile --> docker__ai_tools__entrypoint__print
    llx__tools__model_manager__ModelManager__benchmark_model --> docker__ai_tools__entrypoint__print
    llx__ModelManager__cleanup_unused_models --> docker__ai_tools__entrypoint__print
    llx__tools__model_manager__ModelManager__print_model_summary --> docker__ai_tools__entrypoint__print
    llx__cli__formatters__print_models_table --> llx__cli__formatters___filter_models
    llx__cli__formatters__print_models_table --> llx__cli__formatters___build_title
    llx__cli__formatters__print_models_table --> llx__cli__formatters___render_models_table
    llx__cli__formatters__print_models_table --> llx__cli__formatters___build_model_row
    llx__cli__formatters___render_tools_table --> llx__analysis__runner__check_tool
    llx__cli__formatters__print_info_tables --> llx__cli__formatters___render_tools_table
    llx__cli__formatters__print_info_tables --> llx__cli__formatters___render_tiers_table
    llx__cli__formatters__print_info_tables --> llx__cli__formatters___render_tags_legend
    llx__cli__formatters__print_info_tables --> llx__cli__formatters___render_agents_table
    llx__HealthChecker__run_comprehensive_health_check --> docker__ai_tools__entrypoint__print
    llx__HealthChecker___print_health_summary --> docker__ai_tools__entrypoint__print
    llx__HealthChecker__run_quick_health_check --> docker__ai_tools__entrypoint__print
    llx__tools__health_checker__HealthChecker__monitor_services --> docker__ai_tools__entrypoint__print
    llx__litellm_config__load_litellm_config --> llx__litellm_config__LiteLLMConfig__load
    llx__orchestration__rate_limiter__RateLimiter__load_limits --> docker__ai_tools__entrypoint__print
    llx__orchestration__rate_limiter__RateLimiter__save_limits --> docker__ai_tools__entrypoint__print
    llx__orchestration__rate_limiter__RateLimiter__add_limit --> docker__ai_tools__entrypoint__print
    llx__orchestration__rate_limiter__RateLimiter__remove_limit --> docker__ai_tools__entrypoint__print
    llx__RateLimiter___apply_penalty --> docker__ai_tools__entrypoint__print
    llx__RateLimiter___cleanup_worker --> docker__ai_tools__entrypoint__print
    llx__RateLimiter___cleanup_expired_penalties --> docker__ai_tools__entrypoint__print
    llx__RateLimiter__print_status_summary --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI__run_command --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_start --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_stop --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_restart --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_status --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_health --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_monitor --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_vscode --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_llm --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_route --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_queue --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_rate_limit --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_session --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_instance --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_config --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___handle_utils --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___benchmark_routing --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___benchmark_rate_limiting --> docker__ai_tools__entrypoint__print
    llx__OrchestratorCLI___benchmark_queue --> docker__ai_tools__entrypoint__print
    llx__cli__app__select --> llx__config__LlxConfig__load
    llx__cli__app__select --> llx__analysis__collector__analyze_project
    llx__cli__app__select --> llx__routing__selector__select_model
    llx__cli__app__chat --> llx__config__LlxConfig__load
    llx__cli__app__chat --> llx__analysis__collector__analyze_project
    llx__cli__app__proxy_start --> llx__config__LlxConfig__load
    llx__cli__app__proxy_start --> llx__integrations__proxy__start_proxy
    llx__cli__app__proxy_config --> llx__config__LlxConfig__load
    llx__cli__app__proxy_config --> llx__integrations__proxy__generate_proxy_config
    llx__cli__app__proxy_status --> llx__config__LlxConfig__load
    llx__cli__app__proxy_status --> llx__integrations__proxy__check_proxy
    llx__cli__app__models --> llx__config__LlxConfig__load
    llx__cli__app__models --> llx__cli__formatters__print_models_table
    llx__cli__app__info --> llx__cli__formatters__print_info_tables
    llx__cli__app__info --> llx__config__LlxConfig__load
    llx__cli__app___run_analysis_tools --> llx__analysis__runner__run_all_tools
    llx__LLMOrchestrator__load_config --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__save_config --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator___create_default_config --> docker__ai_tools__entrypoint__print
    llx__orchestration__llm_orchestrator__LLMOrchestrator__start --> docker__ai_tools__entrypoint__print
    llx__orchestration__llm_orchestrator__LLMOrchestrator__stop --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__add_provider --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__remove_provider --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__add_model --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__complete_request --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__cancel_request --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator___health_check_worker --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator___config_save_worker --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator___perform_health_checks --> docker__ai_tools__entrypoint__print
    llx__LLMOrchestrator__print_status_summary --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine__load_config --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine__save_config --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine__route_request --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine___metrics_worker --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine___optimization_worker --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine___optimize_routing --> docker__ai_tools__entrypoint__print
    llx__RoutingEngine__print_status_summary --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__load_config --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__save_config --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator___create_default_config --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__start --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__stop --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__add_account --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__remove_account --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__create_instance --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__remove_instance --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__start_instance --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__end_session --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator___start_browser_for_instance --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator___session_cleanup_worker --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator___config_save_worker --> docker__ai_tools__entrypoint__print
    llx__VSCodeOrchestrator__print_status_summary --> docker__ai_tools__entrypoint__print
    llx__mcp__server__main_sync --> llx__mcp__server__main
    llx__integrations__proxy__start_proxy --> llx__integrations__proxy__generate_proxy_config
    llx__mcp__tools___handle_llx_analyze --> llx__config__LlxConfig__load
